### ISSUE TITLE
Error in Demographics module 

### ISSUE THREAD

**Issue by romulus** [synthetichealth/synthea#317] opened 2018-05-30 19:23 UTC
I have just downloaded synthea and tried to follow the instructions. 
I am able to run it successfully with or without parameters for only Massachusetts. 
Any time I try to specify any other state or state [city], I get either unknown city error or unable to load demographics module. I checked the demographics.csv file and verified that the state or state city pairs I specify are actually available. Even the same example from the readme, ./run_synthea Utah "Salt Lake City" causes the same error. Can anyone help me to understand what  I am missing as i dont see this error on the issues previously

**Comment by dehall** [comment] 2018-05-31 11:40
Could you post the full output and error message that you're seeing?

**Comment by sshellmann** [comment] 2018-05-31 13:07
./run_synthea Utah "Salt Lake City"
> Task :run FAILED
ERROR: unable to load demographics
java.lang.Exception: The city Salt Lake City was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:47)
        at org.mitre.synthea.engine.Generator.init(Generator.java:133)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:106)
        at App.main(App.java:83)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:63)
        at org.mitre.synthea.engine.Generator.init(Generator.java:133)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:106)
        at App.main(App.java:83)
Caused by: java.lang.Exception: The city Salt Lake City was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:47)
        ... 3 more

The error is being caused by the options processing. It is checking against an empty state at: https://github.com/synthetichealth/synthea/blob/master/src/main/java/App.java#L68
but the state is initially set to Massachusetts at:
https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/engine/Generator.java#L65

If you follow the option parsing logic, the initial set to DEFAULT_STATE causes it to ignore what was passed in. This means you can only ever do cities in the DEFAULT_STATE, Massachusetts.

**Comment by murflaw7424** [comment] 2018-05-31 15:34
I ran the changes that you committed to GitHub and these work perfectly!  Thank you!

Also, I ram for Miami, FL with no issues.

**Closed** 2018-05-31 20:36 UTC

**Comment by ieezeume** [comment] 2023-05-27 02:21
Hello,

For some reason, I am getting the same error when I try  ./run_synthea Michigan "Baraga". Please how can I resolve it?

**Comment by ieezeume** [comment] 2023-05-30 13:27
I changed .csv export to true and tried the latest version and v3.1.1. I am using ubuntu vm.
![A98675CD-ADB6-4E89-8661-A827326B4BE8_1_105_c](https://github.com/synthetichealth/synthea/assets/115907457/c658a0d8-7165-4a70-8338-7977cbb918f3)
![1674D0DF-BDA2-47C5-9A53-04FE5AA2B494_1_105_c](https://github.com/synthetichealth/synthea/assets/115907457/a99fa27e-b8ce-4c99-b38f-384d22551d93)

**Comment by ieezeume** [comment] 2023-05-30 13:30
sudo ./run_synthea -p 18  Michigan “Houghton” --config covid19 

> Task :run FAILED
ERROR: unable to load demographics
java.lang.Exception: The city “Houghton” was not found in the demographics file for state Michigan.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:74)
        at org.mitre.synthea.engine.Generator.init(Generator.java:226)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:208)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:184)
        at App.main(App.java:229)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:102)
        at org.mitre.synthea.engine.Generator.init(Generator.java:226)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:208)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:184)
        at App.main(App.java:229)
Caused by: java.lang.Exception: The city “Houghton” was not found in the demographics file for state Michigan.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:74)
        ... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3s
4 actionable tasks: 2 executed, 2 up-to-date

**Comment by dehall** [comment] 2023-05-30 13:48
`sudo ./run_synthea -p 18 Michigan “Houghton” --config covid19`

It looks like those quotes are the special character versions `“”` and not the usual `""`, so the program is looking for a city with the literal name `“Houghton”` including those quotes which doesn't exist.

Can you try running it without the quotes? 

If you want to run it for a city or state with a space in the name you will still need to use quotes but make sure they are the standard "" and not for example the smart quotes that MS Office products sometimes replace them with.
