### ISSUE TITLE
Failures during current build

### ISSUE THREAD

**Issue by DSSUSER** [synthetichealth/synthea#741] opened 2020-06-30 21:15 UTC
I was getting a lot of errors on the screen during the most recent build, and most of what I was seeing, toward the end, were related to Covid-19.

However, I decided to create my own logfile, to capture the output.

I ran the following command to gather the most complete logfile entries I could get:

cd /opt/synthea

cat /dev/null > /var/log/synthea_build.log

./gradlew --stacktrace --debug --scan build check test | tee /var/log/synthea_build.log

These are the errors I am finding:  (Most are due to a missing Covid-19 CSV file.)

2020-06-30T20:01:51.324+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.ModuleTest > getModules FAILED
2020-06-30T20:01:51.324+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid19_prob.csv not found.

2020-06-30T20:01:51.732+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.ModuleTest > addLocalModules FAILED
2020-06-30T20:01:51.732+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid19_prob.csv not found.

2020-06-30T20:01:51.760+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.ModuleTest FAILED

2020-06-30T20:02:13.509+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGeneratePeopleDefaultLocation FAILED
2020-06-30T20:02:13.536+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:02:25.064+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testOnlyAliveAndDead FAILED
2020-06-30T20:02:25.064+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:02:36.230+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testDemographicsRetry FAILED
2020-06-30T20:02:36.230+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:02:47.314+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testUpdateAfterCreationAndSerialization FAILED
2020-06-30T20:02:47.314+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:02:59.088+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateRecordQueue FAILED
2020-06-30T20:02:59.088+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:03:09.353+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateWithMetrics FAILED
2020-06-30T20:03:09.353+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:03:21.583+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGeneratePeopleByLocation FAILED
2020-06-30T20:03:21.583+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:03:33.881+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateOnlyDeadPatients FAILED
2020-06-30T20:03:33.882+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:03:44.422+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateOnlyAlivePatients FAILED
2020-06-30T20:03:44.422+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:03:56.633+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateWithDatabase FAILED
2020-06-30T20:03:56.633+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:04:07.001+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGeneratorCreatesPeople FAILED
2020-06-30T20:04:07.001+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:04:18.236+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testGenerateWithDetailedLogLevel FAILED
2020-06-30T20:04:18.242+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:04:28.533+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest > testUpdateAfterCreation FAILED
2020-06-30T20:04:28.533+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:04:28.553+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.engine.GeneratorTest FAILED

2020-06-30T20:04:35.028+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRDSTU2ExporterTest > testFHIRDSTU2Export FAILED
2020-06-30T20:04:35.028+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:04:35.040+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRDSTU2ExporterTest FAILED

2020-06-30T20:05:38.422+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.TextExporterTest > testTextExport FAILED
2020-06-30T20:05:38.422+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:05:38.435+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.TextExporterTest FAILED

2020-06-30T20:06:03.590+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.SymptomCSVExporterTest > testSymptomCSVExport FAILED
2020-06-30T20:06:03.591+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:03.612+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.SymptomCSVExporterTest FAILED

2020-06-30T20:06:22.772+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
2020-06-30T20:06:22.779+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:22.829+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CCDAExporterTest FAILED

2020-06-30T20:06:27.667+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CSVExporterTest > testDeferredCSVExport FAILED
2020-06-30T20:06:27.668+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:27.691+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CSVExporterTest FAILED

2020-06-30T20:06:35.510+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRSTU3ExporterTest > testFHIRSTU3Export FAILED
2020-06-30T20:06:35.510+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:35.530+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRSTU3ExporterTest FAILED

2020-06-30T20:06:50.408+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CDWExporterTest > testCDWExport FAILED
2020-06-30T20:06:50.409+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:50.429+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CDWExporterTest FAILED

2020-06-30T20:06:56.642+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRR4ExporterTest > testFHIRR4Export FAILED
2020-06-30T20:06:56.643+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:06:56.694+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.FHIRR4ExporterTest FAILED

2020-06-30T20:07:03.655+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.SymptomTextExporterTest > testSymptomTextExport FAILED
2020-06-30T20:07:03.655+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:07:03.677+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.SymptomTextExporterTest FAILED

2020-06-30T20:07:09.650+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CPCDSExporterTest > testCPCDSExport FAILED
2020-06-30T20:07:09.651+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:07:09.710+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.export.CPCDSExporterTest FAILED

2020-06-30T20:09:01.488+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.world.agents.PersonTest > testSerializationAndDeserialization FAILED
2020-06-30T20:09:01.488+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:09:01.508+0000 [DEBUG] [TestEventLogger] org.mitre.synthea.world.agents.PersonTest FAILED

2020-06-30T20:12:05.835+0000 [DEBUG] [TestEventLogger] AppTest > testApp FAILED
2020-06-30T20:12:05.835+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:12:07.258+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithAges FAILED
2020-06-30T20:12:07.258+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:12:08.789+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithConfigSetting FAILED
2020-06-30T20:12:08.790+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:12:24.905+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithDifferentLocation FAILED
2020-06-30T20:12:24.905+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:12:26.196+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithGender FAILED
2020-06-30T20:12:26.197+0000 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.IllegalArgumentException: resource generic/lookup_tables/covid-19-severity-outcomes.csv not found.

2020-06-30T20:12:27.460+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithLocalConfigFile FAILED

2020-06-30T20:12:28.478+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithLocalModuleDir FAILED

2020-06-30T20:12:29.457+0000 [DEBUG] [TestEventLogger] AppTest > testAppWithModuleFilter FAILED

2020-06-30T20:12:29.489+0000 [DEBUG] [TestEventLogger] AppTest FAILED

2020-06-30T20:12:29.490+0000 [DEBUG] [TestEventLogger] Gradle Test Executor 5 FAILED

2020-06-30T20:12:31.188+0000 [DEBUG] [TestEventLogger] Gradle Test Run :test FAILED

2020-06-30T20:12:31.463+0000 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :test FAILED

**Comment by jawalonoski** [comment] 2020-07-06 20:12
I am unable to replicate these errors locally. 

Do you have the fixes from #736?

Can you update and see if these persist?

Do you have any local changes?

**Comment by jawalonoski** [comment] 2020-12-16 00:14
No follow up, so I am closing this issue: unable to reproduce.

**Closed by jawalonoski** 2020-12-16 00:14 UTC
