### ISSUE TITLE
Getting Java Null Pointer exceptions running on Mac OSX

### ISSUE THREAD

**Issue by rjcampion3** [synthetichealth/synthea#506] opened 2019-04-23 20:25 UTC
I did a pull yesterday and I get the following errors when performing the ./run_synthea from the command line:

Population: 10
Seed: 1556050888206
Location: Massachusetts
Min Age: 0
Max Age: 140
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
{alive=0, dead=0}

PC Info: Mac OSX Mojave 10.14.3

Java Info:
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**Comment by jamesagnew** [comment] 2019-04-23 20:44
Without knowing much about this specific issue, I'd bet the issue is more about the use of JDK 12 than it is about OSX... I've had a few things fail on this new version.

**Comment by rjcampion3** [comment] 2019-04-24 14:56
Downgraded to Java SDK 10:
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

I did a git reset --hard origin/master and then did a new ./gradlew build check test and the tests fail with the same errors. I tried a new run using the command ./run_synthea -p 10 and the following errors occurred. 

And I still get the following errors:

Running with options:
Population: 10
Seed: 1556117467152
Location: Massachusetts
Min Age: 0
Max Age: 140
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:220)
        at org.mitre.synthea.engine.State.run(State.java:150)
        at org.mitre.synthea.engine.Module.process(Module.java:212)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:317)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
{alive=0, dead=0}

Am I missing a setting? Is there anything else I can provide to help troubleshoot the issue? 

Thanks,
Rick

**Comment by rjcampion3** [comment] 2019-04-24 16:03
I downloaded and ran it on Windows with JDK 10 and it worked. Must be something with OSX and My java version. I'll play around with uninstalling java and go that route first. 

Thanks,
Rick

**Comment by jawalonoski** [comment] 2019-04-24 18:28
Right now we're developing using JDK 8, and Travis is only configured for JDK 8.

**Comment by jawalonoski** [comment] 2019-04-24 18:45
Running an experiment with #507 ...

**Comment by jawalonoski** [comment] 2019-04-30 12:58
#507 suggests that OpenJDK 8, 11, and 12 work correctly.

Since JDK 10 has been superseded (https://jdk.java.net/10/), I do not intend to support it.

We can reopen this issue if others have trouble, but I'm going to close this for now.

**Closed by jawalonoski** 2019-04-30 12:58 UTC
