### ISSUE TITLE
Exception in setVitalSign

### ISSUE THREAD

**Issue by drwallace2** [synthetichealth/synthea#1038] opened 2022-04-05 16:33 UTC
### What happened?

We are generating a large patient population by running multiple synthea processes on blocks of 70000 patients each.
Our command line is:

`java -Xmx32g -jar synthea_with_dependencies.jar Maine -p 70000 -c synthea.properties --exporter.baseDirectory output/output${thread} --exporter.csv.append_mode true  > logs/script.log.$(thread)`

The process fails rarely,  approximately once in every 15 executions, with the following exception:

```
java.lang.IllegalArgumentException: Vital signs must have finite values - \
NaN is invalid                                                                                                     
        at org.mitre.synthea.world.agents.Person.setVitalSign(Person.java:441)                                     
        at org.mitre.synthea.modules.WeightLossModule.manageYearTwoThroughFive(WeightLossModule.java:164)          
        at  ... etc.
```

### Environment

```markdown
- OS: Linux 3.10.0-1160.59.1.el7.x86_64
- Java:
openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1-LTS, mixed mode, sharing)
```

**Comment by eedrummer** [comment] 2022-04-13 21:46
I don't have a fix for this yet, but I have made some progress on identifying the cause.

Individuals who start weight management at age 13 can cause issues for the `transitionRegression` method. For this method to be invoked, someone must start weight management under age 20, be successful for a year, then regress, where the regression would complete after age 20. The code here is complicated because weight management is different under age 20, when people are still growing and it is BMI-percentile based, to after 20 where it is purely percentage of weight based. This method attempts to have the individual gain weight at a biologically plausible pace and attempts to avoid an odd transition around age 20.

The case here seems like it would be pretty rare, as I think the only way to get a `NaN` is to have weight management start on exactly the person's 13th birthday and then request a weight on exactly their 20th birthday, causing a zero divided by zero in the method.

I'm surprised that we don't see this error more often with vital signs complaining that weight is set to `Infinity`. The surrounding logic may protect against that.

**Comment by eedrummer** [comment] 2022-05-31 18:28
I will assume the the referenced PR addressed your issue. If not, feel free to reopen.

**Closed by eedrummer** 2022-05-31 18:28 UTC
Labels: bug

**Comment by arvindshmicrosoft** [comment] 2023-10-07 18:08
@eedrummer I got this exception with a build from commit 6192ed703d8517e7bfab801d9fbee622ec4e8161 (latest as of 2023-10-07). Please let me know if it's more appropriate to open a new issue for this.

```
java.lang.IllegalArgumentException: Vital signs must have finite values - NaN is invalid
        at org.mitre.synthea.world.agents.Person.setVitalSign(Person.java:486)
        at org.mitre.synthea.modules.WeightLossModule.manageYearTwoThroughFive(WeightLossModule.java:165)
        at org.mitre.synthea.modules.WeightLossModule.process(WeightLossModule.java:82)
        at org.mitre.synthea.engine.Generator.updatePerson(Generator.java:712)
        at org.mitre.synthea.engine.Generator.createPerson(Generator.java:668)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:478)
        at org.mitre.synthea.engine.Generator.lambda$run$3(Generator.java:383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The command line was:

`java -Xmx24G -jar ./build/libs/synthea-with-dependencies.jar --exporter.fhir.export false --exporter.csv.export true --exporter.baseDirectory '/synthea_data/Arizona Phoenix 706' --generate.log_patients.detail none --exporter.clinical_note.export false -p 781512 Arizona Phoenix`

Relevant output from the process:
```
Running with options:
Population: 781512
Seed: 1696672364458
Provider Seed:1696672364458
Reference Time: 1696672364458
Location: Phoenix, Arizona
Min Age: 0
Max Age: 140
```

Environment details in case it's helpful:

Java:
```
openjdk 11.0.20 2023-07-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.20.0.8-1) (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.20.0.8-1) (build 11.0.20+8-LTS, mixed mode, sharing)
```

OS:
```
Linux version 4.18.0-425.10.1.el8_7.x86_64 (mockbuild@dal1-prod-builder001.bld.equ.rockylinux.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-15) (GCC)) #1 SMP Thu Jan 12 16:32:13 UTC 2023
```
