### ISSUE TITLE
Failed to post R4 bundle to HAPI

### ISSUE THREAD

**Issue by MrigendraKumar** [synthetichealth/synthea#1005] opened 2022-02-11 02:16 UTC
Getting Below error while posting R4 bundle to HAPI fhir server.

{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to extract values from resource using FHIRPath &quot;Encounter.participant.individual.where(resolve() is Practitioner)&quot;: org.hl7.fhir.exceptions.FHIRException: Unknown resource typesid</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to extract values from resource using FHIRPath \"Encounter.participant.individual.where(resolve() is Practitioner)\": org.hl7.fhir.exceptions.FHIRException: Unknown resource typesid"
    }
  ]
}

**Comment by jawalonoski** [comment] 2022-02-11 13:36
Did you post these files _first_?

```
./output/fhir/hospitalInformation*.json
./output/fhir/practitionerInformation*.json
```

That data needs to be loaded _before_ each patient record.

**Comment by jamesagnew** [comment] 2022-02-11 14:59
I've tripped over this as well.. I could be wrong but I believe the issue isn't absolute references, it's search references. E.g.

```
{
   "practitioner": { "reference": "Practitioner?identifier=foo|bar" }
}
```

These are allowed in HAPI FHIR but only if explicitly enabled, and if they're disabled you get that (really unhelpful) error. I keep meaning to look into this - We set that feature to default disabled because it was non-standard a long time ago. I wonder if that has changed?

**Comment by jawalonoski** [comment] 2022-02-11 15:41
I just checked out https://github.com/hapifhir/hapi-fhir-jpaserver-starter and locally ran an empty clean version of HAPI.

I then posted the organizations, and then the practitioners, and then the patients.

They all load fine without error.

I then added all the Practitioners a second time. I tried to load a patient record and got an OperationOutcome that said `Invalid match URL \"Practitioner?identifier=http://hl7.org/fhir/sid/us-npi|9999999479\" - Multiple resources match this search`

Which is interesting, because I noticed that on `hapi.fhir.org` there are many Practitioner resources that share the same identifiers (_because so many people are loading Synthea data onto it_), but that is NOT the same error as @MrigendraKumar posted.

I believe this issue has something to do with the fact that on `hapi.fhir.org` there are _so many people are posting Synthea data_ that the search references are matching multiple resources... where perhaps one of those resources is missing some information that the FHIR Path is choking on. Not sure.

**Comment by jamesagnew** [comment] 2022-02-11 16:57
It occurs to me we changed the default of "allow inline match URLs" to enabled a while back. @MrigendraKumar which version of HAPI FHIR are you using? If not the latest, I'd recommend upgrading.

@jawalonoski yeah, that is probbaly right. Has there ever been any discussion around changing `practitionerInformation` and `hospitalInformation` to perform conditional creates?

**Comment by jawalonoski** [comment] 2022-02-11 17:28
@jamesagnew Yes, I think we already do that using the `ifNoneExist` attribute, e.g.,

```json
    "request": {
      "method": "POST",
      "url": "Practitioner",
      "ifNoneExist": "identifier=http://hl7.org/fhir/sid/us-npi|9999999995"
    }
```

```json
    "request": {
      "method": "POST",
      "url": "Organization",
      "ifNoneExist": "identifier=https://github.com/synthetichealth/synthea|ef58ea08-d883-3957-8300-150554edc8fb"
    }
```

**Comment by jamesagnew** [comment] 2022-02-11 18:13
Oh weird.. I wonder why there's duplicates then. I guess if someone was uploading the bundle multiple times concurrently this could happen, but that seems unlikely. (we do support unique identifier constraints, but none are active on the public server)

**Comment by jamesagnew** [comment] 2022-02-11 18:13
Wait, for that matter, how did you upload yours? If should be completely idempotent to upload that bundle multiple times in that case...

**Comment by jawalonoski** [comment] 2022-03-04 13:23
@jamesagnew I'm tempted to close this issue because we can't recreate it. Do you want to create an issue on HAPI for this, or have me leave it open?

**Closed** 2022-03-04 13:32 UTC
