### ISSUE TITLE
Use claims/admin data as the source

### ISSUE THREAD

**Issue by farbodr** [synthetichealth/synthea#226] opened 2017-09-10 13:53 UTC
Are there any plans to extend this to use claims data to generate clinical data? For instance, I have de-identified claims data for a population of 1 million going back 5 years. What I'm missing is clinical data to match the claims. 

TIA,
FR

**Comment by jawalonoski** [comment] 2017-09-10 19:01
No, we do not plan to generate clinical data given a set of claims as inputs.

However, we are adding the generation of Claims to match the synthetic record.

**Comment by dantohe** [comment] 2017-10-04 17:32
What is the timeline for adding the claims data. Thanks!

**Comment by jawalonoski** [comment] 2017-10-04 17:36
@dantohe There is a `claims` branch right now that you can checkout and play with. It needs work, especially in terms of realistic costs (non-trivial), but if you use that branch FHIR Claims will be generated. I don't have a set timeline to merge that branch. Maybe by November.

**Comment by dantohe** [comment] 2017-10-18 16:00
Jason,
is there a way to properly optimize the multi threading (any advise will help) - what I see in the synthea.yml:
    thread_pool_size:
    # numbers picked by experimentation on 2013 i5 mbp, may need to be tweaked on less powerful systems
    # consider SSD vs HDD, # of cpus/cores, memory usage, etc
      city_workers: 4
      generate_workers: 6
      export_workers: 10

Thanks a lot!
Daniel

**Comment by jawalonoski** [comment] 2017-10-23 15:18
@dantohe Trial and error.

Rules of thumb: 
* You want more `export_workers` than `generate_workers` and you want more `generate_workers` than `city_workers`.
    * This is because exporting (writing to disk) is the slowest process (and the bottleneck).
* You _probably_ want the total number of workers to be less than the number of CPU Cores you have on your system and all the processes to fit within available memory (RAM), otherwise you might see thrashing between CPU/cache/RAM/swap depending on your parameters.

**Comment by jawalonoski** [comment] 2017-10-25 19:35
The `claims` branch is now merged into `master`

**Comment by dantohe** [comment] 2017-10-30 15:20
Jason - thanks a lot!

I just cloned the latest version of the master and generated some patients.
I see claims in the  fhir (as opossed to fhir_dstu2) but I cannot find anything in the ccda. I am using the same patient as reference.
Is this the expected behavior?

Thanks

Daniel

**Comment by dantohe** [comment] 2017-10-30 15:59
Jason - one more thing I am noticing while generating patients this morning: txt and csv formats are no generated. The only content I find in the text folder is hospital_information.txt while in the CSV I see only headers in the corresponding files (and nothing else).

**Comment by jawalonoski** [comment] 2017-10-30 16:01
Yes, this is the expected behavior.

We only generate claims for FHIR STU3 at this point.

The other export formats can be updated to export claims, but we have not done so at this time. 

Frankly, I don't know enough about C-CDA R2.1 to properly export claims... In fact, I didn't even think it was possible. Looking through the specification, I don't see any obvious way to include these.

**Comment by jawalonoski** [comment] 2017-10-30 16:05
@dantohe Did you enable those formats in the `config/synthea.yml` file? If you recently updated, your configuration file may have been overwritten.

**Comment by dantohe** [comment] 2017-10-30 16:06
I double checked the config and csv and txt are enabled.

**Comment by jawalonoski** [comment] 2017-10-30 16:12
Yep, that's a bug... fixing...

**Comment by dantohe** [comment] 2017-10-30 16:13
thanks

**Comment by jawalonoski** [comment] 2017-10-30 16:16
Fixed with d600964

**Comment by dantohe** [comment] 2017-11-01 18:39
Looks good now!
Thanks for fast turnover.

**Closed** 2017-11-01 18:57 UTC
