### ISSUE TITLE
task versionTxt failed on build 

### ISSUE THREAD

**Issue by cah-ext-yaswanthparasa** [synthetichealth/synthea#468] opened 2019-01-24 11:56 UTC

**Comment by cah-ext-yaswanthparasa** [comment] 2019-01-24 11:56
on trying to task version txt always fails how to resolve the same

**Comment by jawalonoski** [comment] 2019-01-29 16:37
Unless some more information is provided I'm going to have to close this issue with a resolution of "not enough information" or "cannot reproduce".

**Closed** 2019-01-30 14:04 UTC
