### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by SQLDataNinja** [synthetichealth/synthea#326] opened 2018-06-06 22:13 UTC
Thanks for everyone's work on this project, such an awesome application. I just cloned the project repository per the instructions on the wiki; however, not sure if this is expected behavior, but when i run the program I am receiving many NullPointerExceptions around Location.assignPoint.

Run Command:
run_synthea -p 5000 Pennsylvania 

src/main/resource/synthea.properties Changes: 
exporter.csv.export = true

**Comment by dehall** [comment] 2018-06-06 22:27
Thanks for pointing this out. Looks like there's a discrepancy in naming conventions between our data sources for Pennsylvania location names, where one data source includes "borough" at the end (ex, "Abbottstown borough") and one does not. Other states may be affected as well.

I'll try to get a PR in to fix this as soon as possible.

**Comment by murflaw7424** [comment] 2018-06-07 02:54
I can confirm that NJ is affected by that issue.

**Comment by ShreyaPrasad31** [comment] 2018-06-07 14:57
I agree with how amazing this application is! 
I'm having  NullPointerExceptions even when i run 
run_synthea without any additional parameters

Same changes as in Properties file 
exporter.csv.export = true

**Comment by jawalonoski** [comment] 2018-06-20 11:06
_**Some**_ of these NPE should have been fixed with #330.

More to come.

**Closed** 2019-02-12 21:20 UTC
Labels: bug
